import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto, Outfit } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";

const outfitHeading = Outfit({subsets:['latin'],variable:'--font-heading'});

const roboto = Roboto({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={cn(
          "min-h-full flex flex-col antialiased",
          "bg-gradient-to-br from-blue-50 to-indigo-100",
          // Injecting all font variables
          geistSans.variable,
          geistMono.variable,
          roboto.variable,
          outfitHeading.variable,
          // Applying the default sans font (Roboto) to the body
          "font-sans text-slate-900" 
        )}
      >
        <TooltipProvider>{children}</TooltipProvider>
      </body>
    </html>
  );
}